<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'VyOSElasticModernFulltextStorageEngine' => 'engine/VyOSElasticModernFulltextStorageEngine.php',
    'VyOSElasticModernFulltextStorageEngineTestCase' => '__tests__/VyOSElasticModernFulltextStorageEngineTestCase.php',
    'VyOSElasticModernFulltextStorageEngineTestDouble' => '__tests__/VyOSElasticModernFulltextStorageEngineTestCase.php',
    'VyOSElasticModernHost' => 'host/VyOSElasticModernHost.php',
    'VyOSElasticModernHostTestCase' => '__tests__/VyOSElasticModernHostTestCase.php',
  ),
  'function' => array(),
  'xmap' => array(
    'VyOSElasticModernFulltextStorageEngine' => 'PhabricatorFulltextStorageEngine',
    'VyOSElasticModernFulltextStorageEngineTestCase' => 'PhutilTestCase',
    'VyOSElasticModernFulltextStorageEngineTestDouble' => 'VyOSElasticModernFulltextStorageEngine',
    'VyOSElasticModernHost' => 'PhabricatorSearchHost',
    'VyOSElasticModernHostTestCase' => 'PhutilTestCase',
  ),
));
